### ISSUE TITLE
Not synced?

### ISSUE THREAD

**Issue by modocache** [delcypher/llvm-lit#1]
How often is this mirror synced? It looks like https://github.com/llvm-mirror/llvm/tree/master/utils/lit was last updated 19 days ago, but that change hasn't been reflected in this repository.

<img width="1001" alt="screen shot 2015-12-07 at 6 13 41 pm" src="https://cloud.githubusercontent.com/assets/552921/11642847/478dbbf0-9d0e-11e5-98a8-3eca7960e253.png">

Any plans to sync in the near future?

**Comment by delcypher** [comment]
@modocache This repository is no longer synced. I originally set this up so I could have other (non LLVM) projects pull this in as a submodule but then I discovered `llvm-lit` is available on PyPi as `lit`.
See https://pypi.python.org/pypi/lit

If you think there is a good use case for setting this mirror back up I can do it but so far I haven't needed to for my projects.

**Comment by modocache** [comment]
Nah, it's no big deal, just wondering if you were aware.

I was using [Git2Go](http://git2go.com/) to browse this repository; I used this mirror since it didn't take up as much space on my phone as LLVM. I noticed it wasn't fully synced, so I thought to give you a head's up. :wave:
